var SEPARATOR = '|:';
var DP_PATH = '../api/resources/accounts/';

var Config = {
    serverUrl : '../api/',
    edition : '1',
    editionName : 'web',
    assetPath : '',
    tmplatesFolder : "templates",
    phonegap : false,
    viewsArray : [  
                    'HeaderView',
                    'LandingView',
                    'LoginBox',
                    'SignUpBox',
                    'SignUpView',
                    'QuizView',
                    'QuizQuestionView',
                    'DashboardView',
                    'QuizLibraryView',
                    'QuizItemView',
                    'FacDirectoryView',
                    'FacItemView',
                    'FacView',
                    'ModalView',
                    'MySetsView',
                    'InstructionsView',
                    'PackagesView',
                    'PackageItemView',
                    'PracticeView',
                    'ForgotPassView',
                    'ChangePassView',
                    'ReviewView',
                    'ResultsView',
                    'ResumeView',
                    'ResultAnalysisView',
                    'ResultGraphsView',
                    'SolutionsView',
                    'QuestionItemView',
                    'PerformanceView',
                    'FacContactView',
                    'FooterView',
                    'OverView',
                    'LearnMoreView',
                    'ActivityView'
                  ]
};
